### ISSUE TITLE
Classic Fantasy classes not working in v0.3.15

### ISSUE THREAD

**Issue by KenHendo** [RabidOwlbear/osr-character-builder#13]
In v0.3.15 I receive an error when creating a character using a "Classic Fantasy" class.

Error message:   "Compendum pack not found. Ending character creation."

This works normally if I revert to v0.3.14

**Comment by RabidOwlbear** [comment]
This appears to be an issue with the advanced fantasy tome module pointing to a compendium pack in the character builder module that was renamed when localization was added in the 0.3.15 update. I have updated Character builder with a temp fix until the Advanced Fantasy Tome module is updated.
