### ISSUE TITLE
alignment/broken links

### ISSUE THREAD

**Issue by osarusan82** [RabidOwlbear/osr-character-builder#15]
Hi there. Great work on this module!
I'm experience two possible issues on Foundry v11.

First, there is no place to choose alignment when I launch the character builder. Was this removed, or am I missing something?

Second, the journal links to the classes which display at the end of the class description (i.e. Journal: Assassin) are all broken links that do not connect to the compendium.

Thanks again for your hard work!
![Screenshot 2023-10-19 123554](https://github.com/RabidOwlbear/osr-character-builder/assets/7374862/dc1c16f4-0f16-4a09-92fc-4cd39ee56655)

**Comment by RabidOwlbear** [comment]
This issue has been resolved
