### ISSUE TITLE
Advanced Tome Classes not available in character builder in v.0.3.30

### ISSUE THREAD

**Issue by cheapcouches** [RabidOwlbear/osr-character-builder#16]
As title, installing the Advanced Tome module does not add the new classes. I assume this is not intended as issue #14 says that advanced classes should have support, but if this is not a case feel free to ignore.

Screenshot:
![image](https://github.com/RabidOwlbear/osr-character-builder/assets/106628695/3098b345-94f1-48f1-84f0-a11f0cccd22d)
![image](https://github.com/RabidOwlbear/osr-character-builder/assets/106628695/a48ee527-c70b-40f5-8ecb-868e93b85086)

Installed modules: 
![image](https://github.com/RabidOwlbear/osr-character-builder/assets/106628695/ada9f4a1-ae3c-40c9-97f1-81a6b8668592)

Foundry version: V11 build 315
OSE version: 1.10.2

**Comment by RabidOwlbear** [comment]
this has been fixed in update 0.3.33
